### ISSUE TITLE
Mamba config has extra argument

### ISSUE THREAD

**Issue by Hprairie** [facebookresearch/lingua#45]
Hey I got the following traceback:

```bash
[rank0]:[W1103 20:31:35.871728678 CPUAllocator.cpp:249] Memory block of unknown size was allocated before the profiling started, profiler results will not include the deallocation event
[rank0]: Traceback (most recent call last):
[rank0]:   File "<frozen runpy>", line 198, in _run_module_as_main
[rank0]:   File "<frozen runpy>", line 88, in _run_code
[rank0]:   File "/scratch/09753/hprairie/mamba/130m/base2/code/apps/mamba/train.py", line 656, in <module>
[rank0]:     main()
[rank0]:   File "/scratch/09753/hprairie/mamba/130m/base2/code/apps/mamba/train.py", line 652, in main
[rank0]:     train(cfg)
[rank0]:   File "/scratch/09753/hprairie/mamba/130m/base2/code/apps/mamba/train.py", line 551, in train
[rank0]:     eval_args = dataclass_from_dict(EvalArgs, args.eval)
[rank0]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/scratch/09753/hprairie/mamba/130m/base2/code/lingua/args.py", line 45, in dataclass_from_dict
[rank0]:     return OmegaConf.to_object(OmegaConf.merge(base, override))
[rank0]:                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/work/09753/hprairie/ls6/miniconda3/envs/lingua_241028/lib/python3.11/site-packages/omegaconf/omegaconf.py", line 273, in merge
[rank0]:     target.merge_with(*configs[1:])
[rank0]:   File "/work/09753/hprairie/ls6/miniconda3/envs/lingua_241028/lib/python3.11/site-packages/omegaconf/basecontainer.py", line 492, in merge_with
[rank0]:     self._format_and_raise(key=None, value=None, cause=e)
[rank0]:   File "/work/09753/hprairie/ls6/miniconda3/envs/lingua_241028/lib/python3.11/site-packages/omegaconf/base.py", line 231, in _format_and_raise
[rank0]:     format_and_raise(
[rank0]:   File "/work/09753/hprairie/ls6/miniconda3/envs/lingua_241028/lib/python3.11/site-packages/omegaconf/_utils.py", line 819, in format_and_raise
[rank0]:     _raise(ex, cause)
[rank0]:   File "/work/09753/hprairie/ls6/miniconda3/envs/lingua_241028/lib/python3.11/site-packages/omegaconf/_utils.py", line 797, in _raise
[rank0]:     raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
[rank0]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/work/09753/hprairie/ls6/miniconda3/envs/lingua_241028/lib/python3.11/site-packages/omegaconf/basecontainer.py", line 490, in merge_with
[rank0]:     self._merge_with(*others)
[rank0]:   File "/work/09753/hprairie/ls6/miniconda3/envs/lingua_241028/lib/python3.11/site-packages/omegaconf/basecontainer.py", line 514, in _merge_with
[rank0]:     BaseContainer._map_merge(self, other)
[rank0]:   File "/work/09753/hprairie/ls6/miniconda3/envs/lingua_241028/lib/python3.11/site-packages/omegaconf/basecontainer.py", line 432, in _map_merge
[rank0]:     dest[key] = src._get_node(key)
[rank0]:     ~~~~^^^^^
[rank0]:   File "/work/09753/hprairie/ls6/miniconda3/envs/lingua_241028/lib/python3.11/site-packages/omegaconf/dictconfig.py", line 310, in __setitem__
[rank0]:     self._format_and_raise(
[rank0]:   File "/work/09753/hprairie/ls6/miniconda3/envs/lingua_241028/lib/python3.11/site-packages/omegaconf/base.py", line 231, in _format_and_raise
[rank0]:     format_and_raise(
[rank0]:   File "/work/09753/hprairie/ls6/miniconda3/envs/lingua_241028/lib/python3.11/site-packages/omegaconf/_utils.py", line 819, in format_and_raise
[rank0]:     _raise(ex, cause)
[rank0]:   File "/work/09753/hprairie/ls6/miniconda3/envs/lingua_241028/lib/python3.11/site-packages/omegaconf/_utils.py", line 797, in _raise
[rank0]:     raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
[rank0]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/work/09753/hprairie/ls6/miniconda3/envs/lingua_241028/lib/python3.11/site-packages/omegaconf/dictconfig.py", line 308, in __setitem__
[rank0]:     self.__set_impl(key=key, value=value)
[rank0]:   File "/work/09753/hprairie/ls6/miniconda3/envs/lingua_241028/lib/python3.11/site-packages/omegaconf/dictconfig.py", line 318, in __set_impl
[rank0]:     self._set_item_impl(key, value)
[rank0]:   File "/work/09753/hprairie/ls6/miniconda3/envs/lingua_241028/lib/python3.11/site-packages/omegaconf/basecontainer.py", line 545, in _set_item_impl
[rank0]:     self._validate_set(key, value)
[rank0]:   File "/work/09753/hprairie/ls6/miniconda3/envs/lingua_241028/lib/python3.11/site-packages/omegaconf/dictconfig.py", line 180, in _validate_set
[rank0]:     target = self._get_node(key) if key is not None else self
[rank0]:              ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/work/09753/hprairie/ls6/miniconda3/envs/lingua_241028/lib/python3.11/site-packages/omegaconf/dictconfig.py", line 475, in _get_node
[rank0]:     self._validate_get(key)
[rank0]:   File "/work/09753/hprairie/ls6/miniconda3/envs/lingua_241028/lib/python3.11/site-packages/omegaconf/dictconfig.py", line 164, in _validate_get
[rank0]:     self._format_and_raise(
[rank0]:   File "/work/09753/hprairie/ls6/miniconda3/envs/lingua_241028/lib/python3.11/site-packages/omegaconf/base.py", line 231, in _format_and_raise
[rank0]:     format_and_raise(
[rank0]:   File "/work/09753/hprairie/ls6/miniconda3/envs/lingua_241028/lib/python3.11/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
[rank0]:     _raise(ex, cause)
[rank0]:   File "/work/09753/hprairie/ls6/miniconda3/envs/lingua_241028/lib/python3.11/site-packages/omegaconf/_utils.py", line 797, in _raise
[rank0]:     raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
[rank0]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: omegaconf.errors.ConfigKeyError: Key 'mp_size' not in 'EvalArgs'
[rank0]:     full_key: mp_size
[rank0]:     object_type=EvalArgs
```
which comes from the fact that the example config for Mamba has `mp_size: 1` in its eval section. I went ahead and removed it to be consistent with the Llama configs and it resolved the issue. I don't have the bandwidth to open a pr, but I wanted to at least bring this to someone's attention.

Thanks for such a beautiful repo!

**Comment by mathuvu** [comment]
Thank you for your feedback! Should be fix now in #47.
