### ISSUE TITLE
Multi-Node Distributed Issues

### ISSUE THREAD

**Issue by Hprairie** [facebookresearch/lingua#49]
Hey I got the following stack trace:

```python
[rank7]: Traceback (most recent call last):
[rank7]:   File "<frozen runpy>", line 198, in _run_module_as_main
[rank7]:   File "<frozen runpy>", line 88, in _run_code
[rank7]:   File "/scratch/09753/hprairie/mamba/130m/full/code/apps/mamba/train.py", line 656, in <module>
[rank7]:     main()
[rank7]:   File "/scratch/09753/hprairie/mamba/130m/full/code/apps/mamba/train.py", line 652, in main
[rank7]:     train(cfg)
[rank7]:   File "/scratch/09753/hprairie/mamba/130m/full/code/apps/mamba/train.py", line 342, in train
[rank7]:     torch_profiler = context_stack.enter_context(
[rank7]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank7]:   File "/work/09753/hprairie/ls6/miniconda3/envs/lingua_241028/lib/python3.11/contextlib.py", line 517, in enter_context
[rank7]:     result = _enter(cm)
[rank7]:              ^^^^^^^^^^
[rank7]:   File "/work/09753/hprairie/ls6/miniconda3/envs/lingua_241028/lib/python3.11/contextlib.py", line 137, in __enter__
[rank7]:     return next(self.gen)
[rank7]:            ^^^^^^^^^^^^^^
[rank7]:   File "/scratch/09753/hprairie/mamba/130m/full/code/lingua/profiling.py", line 113, in maybe_run_profiler
[rank7]:     os.makedirs(trace_dir, exist_ok=True)
[rank7]:   File "<frozen os>", line 225, in makedirs
[rank7]: FileExistsError: [Errno 17] File exists: '/home1/09753/hprairie/scratch/mamba/130m/full/profiling'
```

which happens when several nodes try to do `os.makedirs(trace_dir, exists_ok=True)`, as a race condition is created by the python's `os` module when using a distributed setup. This is a well known issue of python's os module. I am trying a fix right now, but the following should do it:

This following:
```python
        if not os.path.exists(trace_dir):
            os.makedirs(trace_dir, exist_ok=True)
```

should be changed to

```python
        if not os.path.exists(trace_dir) and get_is_master():
            os.makedirs(trace_dir, exist_ok=True)

        dist.barrier()
```

Again this is only really an issue with multi-node on some file systems, but I thought I should bring it up. I don't have the bandwidth to create a PR, but again wanted to bring it to someone's attention.

**Comment by Hprairie** [comment]
This might also be an issue with the creation of `CheckpointManager` class, as each node could create a race condition attempting to create the folder. For example looking at the [mamba training script](https://github.com/facebookresearch/lingua/blob/31ab231b2d386c4c735e82e8a2c40f10ce13fbbc/apps/mamba/train.py#L312), the `CheckpointManager` is created by each process, which could create race conditions.
